### ISSUE TITLE
Import a weekly CSV of bill data for upcoming hearings

### ISSUE THREAD

**Issue by wzrad** [legislated/legislated-api#3]
Admins should be able to update the CSV generated [here](https://github.com/orgs/engage-il/projects/1#card-2173634) with additional fields: `is_visible`.

We should add a `service` that can ingest this CSV and update the bills accordingly. We can probably just run this service manually through the Heroku console for now.

**Comment by jonrogoff** [comment]
Do you want to consider additional fields: proponent_perspective and opponent_perspective to this story or is that a separate story?

**Comment by wzrad** [comment]
Are those the hand-written summaries that maintainers of the google doc will provide to replace the legalese summary? I think they'd be a great usability improvement at a minor development cost. If so, we should communicate to Kelsey that we want to support the optional [pro|o]pponent summaries in the UI.

**Comment by jonrogoff** [comment]
Yes.  That was exactly my thought.  A couple additional optional fields.  

Whether we do this as 2 additional fields (as described above) or create an entity for positionStatement with separate values for position and statement (and supporters?) is an open question.  The first approach is the quick one that would work best within the csv.  The second one is a bit more flexible to future evolution.

**Comment by jonrogoff** [comment]
May also want to consider ingesting a short summary field that is a bit easier to read and understand than the synopsis.  They are already adding this field to the csv they use now.

**Comment by jonrogoff** [comment]
Perhaps `priority` would be better than `is_visible` allowing for relative prioritization from 1-5 as critical, high, medium, low, ignore?

**Comment by wzrad** [comment]
Hmm, yeah a priority is certainly something to consider. Since we're displaying the bills to user sorted by nearest date, I suppose we group bills by date, and sort each date-group by priority. That'd probably work.

Let's talk about the exact fields we want tonight at Chi Hack Night. Ideally, I'd like to get something simple out the door by next week, so that we can start gathering user feedback and make targeted improvements. At that point, we can also start working on an admin portal that would allow the data wranglers manage these properties without the CSV.
