### ISSUE TITLE
Adopt data structure resembling openstates

### ISSUE THREAD

**Issue by wzrad** [legislated/legislated-api#4]
At some point, we will probably want to migrate some of our scrapers to `openstates` and rely more heavily on their APIs to run our nightly data imports.

In the meantime, we should look at their data model and mirror it more closely in terms of structure and naming, because it's better than ours.

https://openstates.org/api/v1/bills/ILB00099162/

**Comment by wzrad** [comment]
I renamed some of the fields to match openstates more closely and exposed parent structures on the graph in b6f1c46. This allows a bill query to also fetch the associated hearing/committee, for instance.

Anything else from the openstates response / structure you think we should match better in the immediate term, @jonrogoff? I'd like to add the actions, but I don't think we're there yet.

**Comment by jonrogoff** [comment]
Those field changes make sense to me.  I agree that we are not ready for the actions yet.  Eventually, I'd like to confirm their approach to amendments will meet our needs and match that as well, but we are not there yet either.

**Comment by jonrogoff** [comment]
We will need to track session and eventually it will be a top level criterion. Therefore, it might be smart to put that in from the start.

Is bill.type (bill v resolution) simple to grab?  I'm not sure if we will use it, so if it isn't simple don't bother with it.

I expect we will also need an entity rather than a field for sponsors eventually.  I will leave it up to you whether to put that in now or wait until we need it.

**Comment by wzrad** [comment]
I'd avoided making sponsor an entity because we can't scrape an ID for them right now, and we'd have to match them up by name. However, I suppose we'll have to do that anyways for old bill data when we do have a reliable way to get sponsor IDs, so I'll add a sponsor entity as part of this issue.

Not sure about how to get the bill type / session by scraping, but since they're new fields I think we should create a separate issue to track that work. We could probably add a call to the openstates API as part of the `UpdateBillDetailsJob`.

**Comment by jonrogoff** [comment]
I believe the session information is in the query string when pulling the bill info from il.gov, specifically the "GA=100" part.  This is IL General Assembly Session 100.  I have no clue where they are getting the bill type from.
